#!/usr/bin/env python
# -*- coding: utf-8 -*-
#Anders Nelson 04-3-2013

# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# First we import some needed tools, set up our auth, and define some basic variables
import os
import pyrax
import time

creds_file = os.path.expanduser("~/.rackspace_cloud_credentials")
pyrax.set_credential_file(creds_file)

cf = pyrax.cloudfiles

# now we find the local dir we want to upload and check to make sure it is vaild.
x = raw_input('Please enter the path to the directory you would like to upload to cloud files. --> ')

while os.path.isdir(x) == False:
	print "Please enter a valid directory."
	x = raw_input('--> ')
else:
	dir = x
# next we find out the container name.
c = raw_input('Please enter a name for the container you would like to upload to. --> ')

while c.isalnum() != True:
	print "Please enter an alpha numeric container name."
	c = ('--> ')
else:
	con = c
# finally we upload the file to the container

print "Uploading", dir

upload_key, total_bytes = cf.upload_folder(dir, container = con)

#This bit is just to confirm and can be commented out or tweeked

print upload_key

print total_bytes
